name: chess_offline
description: Cross-platform chess app for two people to play chess locally.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: ">=2.18.0-178.0.dev <3.0.0"

dependencies:
  auto_route: ^5.0.1
  font_awesome_flutter: ^10.1.0
  provider: ^6.0.5
  equatable: ^2.0.5
  audioplayers: ^1.1.1

  flutter:
    sdk: flutter

dev_dependencies:
  auto_route_generator: ^5.0.1
  build_runner:

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sound/
